name: Release

on:
    push:
        tags:
            # 支持 giter-v*, ziper-v* 等格式的标签
            - '*-v*'

# 添加全局权限配置
permissions:
    contents: write
    packages: write

jobs:
    get-project:
        runs-on: ubuntu-latest
        outputs:
            project: ${{ steps.set-project.outputs.project }}
            version: ${{ steps.set-version.outputs.version }}
        steps:
            - name: Get project and version from tag
              id: set-project
              run: |
                  TAG=${{ github.ref_name }}
                  PROJECT=$(echo $TAG | cut -d'-' -f1)
                  VERSION=$(echo $TAG | cut -d'-' -f2)
                  echo "project=$PROJECT" >> $GITHUB_OUTPUT
                  echo "Selected project: $PROJECT"

            - name: Set version
              id: set-version
              run: |
                  TAG=${{ github.ref_name }}
                  VERSION=$(echo $TAG | cut -d'-' -f2 | sed 's/^v//')
                  echo "version=$VERSION" >> $GITHUB_OUTPUT
                  echo "Version: $VERSION"

    build-unix:
        needs: get-project
        strategy:
            fail-fast: false
            matrix:
                include:
                    # Linux x64
                    - target: x86_64-unknown-linux-gnu
                    # Linux ARM64
                    - target: aarch64-unknown-linux-gnu

        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Rust toolchain
              uses: dtolnay/rust-toolchain@stable
              with:
                  target: ${{ matrix.target }}

            - name: Install cross
              run: cargo install cross --git https://github.com/cross-rs/cross

            - name: Build Release
              shell: bash
              id: build
              run: |
                  PROJECT=${{ needs.get-project.outputs.project }}
                  VERSION=${{ needs.get-project.outputs.version }}

                  cd package/$PROJECT

                  # 获取二进制名称
                  BINARY_NAME=$(grep "^name\s*=" Cargo.toml | head -n1 | cut -d'"' -f2 || echo "$PROJECT")
                  echo "binary_name=$BINARY_NAME" >> $GITHUB_OUTPUT

                  # 设置输出文件名
                  OUTPUT_NAME="${BINARY_NAME}-${VERSION}-${{ matrix.target }}"

                  # 使用 cross 构建
                  cross build --target ${{ matrix.target }} --release

                  # 复制构建产物
                  cp "target/${{ matrix.target }}/release/${BINARY_NAME}" "$OUTPUT_NAME"

            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ needs.get-project.outputs.project }}-${{ matrix.target }}
                  path: package/${{ needs.get-project.outputs.project }}/${{ steps.build.outputs.binary_name }}-*

    build-windows:
        needs: get-project
        strategy:
            fail-fast: false
            matrix:
                include:
                    - os: windows-latest
                      target: x86_64-pc-windows-msvc
                    - os: windows-latest
                      target: aarch64-pc-windows-msvc

        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4

            - name: Setup Rust toolchain
              uses: dtolnay/rust-toolchain@stable
              with:
                  target: ${{ matrix.target }}

            - name: Build Release
              shell: bash
              id: build
              run: |
                  PROJECT=${{ needs.get-project.outputs.project }}
                  VERSION=${{ needs.get-project.outputs.version }}

                  cd package/$PROJECT

                  # 获取二进制名称
                  BINARY_NAME=$(grep "^name\s*=" Cargo.toml | head -n1 | cut -d'"' -f2 || echo "$PROJECT")
                  echo "binary_name=$BINARY_NAME" >> $GITHUB_OUTPUT

                  # 设置输出文件名
                  OUTPUT_NAME="${BINARY_NAME}-${VERSION}-${{ matrix.target }}.exe"

                  # 原生构建
                  cargo build --target ${{ matrix.target }} --release

                  # 复制构建产物
                  cp "target/${{ matrix.target }}/release/${BINARY_NAME}.exe" "$OUTPUT_NAME"

            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ needs.get-project.outputs.project }}-${{ matrix.target }}
                  path: package/${{ needs.get-project.outputs.project }}/${{ steps.build.outputs.binary_name }}-*

    build-macos:
        needs: get-project
        strategy:
            fail-fast: false
            matrix:
                include:
                    - os: macos-latest
                      target: x86_64-apple-darwin
                    - os: macos-latest
                      target: aarch64-apple-darwin

        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4

            - name: Setup Rust toolchain
              uses: dtolnay/rust-toolchain@stable
              with:
                  target: ${{ matrix.target }}

            - name: Build Release
              shell: bash
              id: build
              run: |
                  PROJECT=${{ needs.get-project.outputs.project }}
                  VERSION=${{ needs.get-project.outputs.version }}

                  cd package/$PROJECT

                  # 获取二进制名称
                  BINARY_NAME=$(grep "^name\s*=" Cargo.toml | head -n1 | cut -d'"' -f2 || echo "$PROJECT")
                  echo "binary_name=$BINARY_NAME" >> $GITHUB_OUTPUT

                  # 设置输出文件名
                  OUTPUT_NAME="${BINARY_NAME}-${VERSION}-${{ matrix.target }}"

                  # 原生构建
                  cargo build --target ${{ matrix.target }} --release

                  # 复制构建产物
                  cp "target/${{ matrix.target }}/release/${BINARY_NAME}" "$OUTPUT_NAME"

            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ needs.get-project.outputs.project }}-${{ matrix.target }}
                  path: package/${{ needs.get-project.outputs.project }}/${{ steps.build.outputs.binary_name }}-*

    release:
        needs: [get-project, build-unix, build-windows, build-macos]
        runs-on: ubuntu-latest
        permissions:
            contents: write
            packages: write
        steps:
            - name: Download all artifacts
              uses: actions/download-artifact@v4

            - name: Create Release
              uses: softprops/action-gh-release@v2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  files: |
                      */*
                  name: ${{ needs.get-project.outputs.project }} ${{ needs.get-project.outputs.version }}
                  draft: false
                  prerelease: false
                  generate_release_notes: true
