name: Release

on:
    push:
        tags:
            # 支持 giter-v*, ziper-v* 等格式的标签
            - '*-v*'

# 添加全局权限配置
permissions:
    contents: write
    packages: write

jobs:
    get-project:
        runs-on: ubuntu-latest
        outputs:
            project: ${{ steps.set-project.outputs.project }}
            version: ${{ steps.set-version.outputs.version }}
        steps:
            - name: Get project and version from tag
              id: set-project
              run: |
                  TAG=${{ github.ref_name }}
                  PROJECT=$(echo $TAG | cut -d'-' -f1)
                  VERSION=$(echo $TAG | cut -d'-' -f2)
                  echo "project=$PROJECT" >> $GITHUB_OUTPUT
                  echo "Selected project: $PROJECT"

            - name: Set version
              id: set-version
              run: |
                  TAG=${{ github.ref_name }}
                  VERSION=$(echo $TAG | cut -d'-' -f2 | sed 's/^v//')
                  echo "version=$VERSION" >> $GITHUB_OUTPUT
                  echo "Version: $VERSION"

    build:
        needs: get-project
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                include:
                    - os: ubuntu-latest
                      target: x86_64-unknown-linux-gnu
                      arch: x86_64
                    - os: ubuntu-latest
                      target: aarch64-unknown-linux-gnu
                      arch: aarch64
                    - os: windows-latest
                      target: x86_64-pc-windows-msvc
                      arch: x86_64
                    - os: windows-latest
                      target: aarch64-pc-windows-msvc
                      arch: aarch64
                    - os: macos-latest
                      target: x86_64-apple-darwin
                      arch: x86_64
                    - os: macos-latest
                      target: aarch64-apple-darwin
                      arch: aarch64

        steps:
            - uses: actions/checkout@v4

            - name: Setup Rust toolchain
              uses: dtolnay/rust-toolchain@stable
              with:
                  targets: ${{ matrix.target }}

            # 安装 OpenSSL 依赖（仅 Linux）
            - name: Install OpenSSL (Ubuntu)
              if: matrix.os == 'ubuntu-latest'
              run: |
                  sudo dpkg --add-architecture arm64
                  sudo apt-get update
                  if [ "${{ matrix.arch }}" = "aarch64" ]; then
                    sudo apt-get install -y --no-install-recommends \
                      gcc-aarch64-linux-gnu \
                      g++-aarch64-linux-gnu \
                      pkg-config \
                      libssl-dev:arm64
                  else
                    sudo apt-get install -y --no-install-recommends \
                      pkg-config \
                      libssl-dev
                  fi

            # 安装 OpenSSL 依赖（仅 macOS）
            - name: Install OpenSSL (macOS)
              if: matrix.os == 'macos-latest'
              run: |
                  brew install openssl@3
                  echo "OPENSSL_DIR=$(brew --prefix openssl@3)" >> $GITHUB_ENV
                  echo "OPENSSL_ROOT_DIR=$(brew --prefix openssl@3)" >> $GITHUB_ENV

            # 安装 Linux ARM64 交叉编译工具
            - name: Install cross-compilation tools (Ubuntu ARM64)
              if: matrix.os == 'ubuntu-latest' && matrix.arch == 'aarch64'
              run: |
                  echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
                  echo "CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
                  echo "CXX_aarch64_unknown_linux_gnu=aarch64-linux-gnu-g++" >> $GITHUB_ENV
                  echo "PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig" >> $GITHUB_ENV

            # 设置 macOS ARM64 交叉编译环境
            - name: Setup macOS ARM64 environment
              if: matrix.os == 'macos-latest' && matrix.arch == 'aarch64'
              run: |
                  echo "MACOSX_DEPLOYMENT_TARGET=11.0" >> $GITHUB_ENV
                  echo "SDKROOT=$(xcrun -sdk macosx --show-sdk-path)" >> $GITHUB_ENV
                  echo "CFLAGS=-target aarch64-apple-darwin" >> $GITHUB_ENV
                  echo "CXXFLAGS=-target aarch64-apple-darwin" >> $GITHUB_ENV
                  echo "RUSTFLAGS=-C target-cpu=apple-a14" >> $GITHUB_ENV

            - name: Build Release
              shell: bash
              id: build
              env:
                  # Linux ARM64 环境变量
                  CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: ${{ matrix.os == 'ubuntu-latest' && matrix.arch == 'aarch64' && 'aarch64-linux-gnu-gcc' || '' }}
                  CC_aarch64_unknown_linux_gnu: ${{ matrix.os == 'ubuntu-latest' && matrix.arch == 'aarch64' && 'aarch64-linux-gnu-gcc' || '' }}
                  CXX_aarch64_unknown_linux_gnu: ${{ matrix.os == 'ubuntu-latest' && matrix.arch == 'aarch64' && 'aarch64-linux-gnu-g++' || '' }}
                  PKG_CONFIG_PATH: ${{ matrix.os == 'ubuntu-latest' && matrix.arch == 'aarch64' && '/usr/lib/aarch64-linux-gnu/pkgconfig' || '' }}
                  
                  # macOS 环境变量
                  MACOSX_DEPLOYMENT_TARGET: ${{ matrix.os == 'macos-latest' && '11.0' || '' }}
                  SDKROOT: ${{ matrix.os == 'macos-latest' && matrix.arch == 'aarch64' && '$(xcrun -sdk macosx --show-sdk-path)' || '' }}
                  CFLAGS: ${{ matrix.os == 'macos-latest' && matrix.arch == 'aarch64' && '-target aarch64-apple-darwin' || '' }}
                  CXXFLAGS: ${{ matrix.os == 'macos-latest' && matrix.arch == 'aarch64' && '-target aarch64-apple-darwin' || '' }}
                  RUSTFLAGS: ${{ matrix.os == 'macos-latest' && matrix.arch == 'aarch64' && '-C target-cpu=apple-a14' || '' }}
                  
                  # OpenSSL 环境变量（macOS）
                  OPENSSL_DIR: ${{ matrix.os == 'macos-latest' && '$(brew --prefix openssl@3)' || '' }}
                  OPENSSL_ROOT_DIR: ${{ matrix.os == 'macos-latest' && '$(brew --prefix openssl@3)' || '' }}
              run: |
                  PROJECT=${{ needs.get-project.outputs.project }}
                  VERSION=${{ needs.get-project.outputs.version }}
                  
                  echo "Current directory: $(pwd)"
                  echo "Project: $PROJECT"
                  echo "Version: $VERSION"
                  
                  # 检查项目目录
                  if [ ! -d "package/$PROJECT" ]; then
                    echo "Error: Project directory package/$PROJECT does not exist"
                    ls -la package/
                    exit 1
                  fi
                  
                  cd package/$PROJECT
                  echo "Changed to directory: $(pwd)"
                  
                  # 获取 Cargo.toml 中的项目名称
                  BINARY_NAME=$(grep "^name\s*=" Cargo.toml | head -n1 | cut -d'"' -f2 || echo "$PROJECT")
                  echo "Binary name from Cargo.toml: $BINARY_NAME"
                  echo "binary_name=$BINARY_NAME" >> $GITHUB_OUTPUT
                  
                  # 设置输出文件名
                  if [ "${{ matrix.os }}" = "windows-latest" ]; then
                    OUTPUT_NAME="${BINARY_NAME}-${VERSION}-${{ matrix.target }}.exe"
                  else
                    OUTPUT_NAME="${BINARY_NAME}-${VERSION}-${{ matrix.target }}"
                  fi
                  
                  echo "Output name: $OUTPUT_NAME"
                  
                  # 构建
                  echo "Building target: ${{ matrix.target }}"
                  cargo build --release --target ${{ matrix.target }}
                  
                  # 验证构建结果
                  if [ $? -ne 0 ]; then
                    echo "Error: Cargo build failed"
                    exit 1
                  fi
                  
                  # 复制构建产物
                  if [ "${{ matrix.os }}" = "windows-latest" ]; then
                    cp "target/${{ matrix.target }}/release/${BINARY_NAME}.exe" "$OUTPUT_NAME"
                  else
                    cp "target/${{ matrix.target }}/release/${BINARY_NAME}" "$OUTPUT_NAME"
                  fi

            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ needs.get-project.outputs.project }}-${{ matrix.target }}
                  path: package/${{ needs.get-project.outputs.project }}/${{ steps.build.outputs.binary_name }}-*

    release:
        needs: [get-project, build]
        runs-on: ubuntu-latest
        # 添加 release job 的权限配置
        permissions:
            contents: write
            packages: write
        steps:
            - name: Download all artifacts
              uses: actions/download-artifact@v4

            - name: Create Release
              uses: softprops/action-gh-release@v2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  files: |
                      */*
                  name: ${{ needs.get-project.outputs.project }} ${{ needs.get-project.outputs.version }}
                  draft: false
                  prerelease: false
                  generate_release_notes: true

